// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBrgnjpJm4OvIdwFwdRyyNJiKSQ0dFB3g0',
    appId: '1:779807337591:web:3938bd908de9006fac2a72',
    messagingSenderId: '779807337591',
    projectId: 'sdvl-coaching',
    authDomain: 'sdvl-coaching.firebaseapp.com',
    storageBucket: 'sdvl-coaching.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC5lErS18hU0C6z0alKd-ieHTIaQchmLrM',
    appId: '1:779807337591:android:bb190ef3a7d445d3ac2a72',
    messagingSenderId: '779807337591',
    projectId: 'sdvl-coaching',
    storageBucket: 'sdvl-coaching.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAZtWmgeK2K9k0hHVDw3aJBWTn0xi6zUbk',
    appId: '1:779807337591:ios:49afcc865fbfe8cbac2a72',
    messagingSenderId: '779807337591',
    projectId: 'sdvl-coaching',
    storageBucket: 'sdvl-coaching.appspot.com',
    iosBundleId: 'com.example.coachingClient',
  );
}
